"""Add User_DisplayName

Revision ID: 6440dde38654
Revises: 861e079e6dc8
Create Date: 2026-06-23 17:18:30.642385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6440dde38654'
down_revision: Union[str, Sequence[str], None] = '861e079e6dc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('User_DisplayName', sa.String(), server_default='User', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'User_DisplayName')
    # ### end Alembic commands ###
